<center><H2> Probability and Statistics</H2></center>
<center><H4>Fernando Deeke Sasse<br></H4></center>
<center><H3>Departamento de Matem√°tica - CCT -  UDESC</H3></center>
<center><H1>Dice Problem</H1></center>

We have 5 dice in a box: 4, 6, 8, 12 and 20-sided dice. Answer the following questions using
Bayesian tables:

Someone picks a die at random, roll it twice and just informs you the results are 9 and 5. Find the probability that the die is 4, 6, 8, 12 and 20-sided.

In [5]:
import pandas as pd
from fractions import Fraction

In [7]:
table = pd.DataFrame(index=[4, 6, 8, 12, 20])
table['prior'] = Fraction(1, 5)
table['likelihood1'] = 0, 0, 0, Fraction(1, 12), Fraction(1, 20)
table['likelihood2'] = 0, Fraction(1, 6), Fraction(1, 8), Fraction(1, 12),  Fraction(1, 20)
table['likelihood'] = table['likelihood1'] * table['likelihood2']
table

   prior likelihood1 likelihood2 likelihood
4    1/5           0           0          0
6    1/5           0         1/6          0
8    1/5           0         1/8          0
12   1/5        1/12        1/12      1/144
20   1/5        1/20        1/20      1/400

Once we have priors and likelhoods, the remaining steps are always the same, so we will put them in a function:

In [9]:
def update(table):
    """Compute the posterior probabilities."""
    table['unnorm'] = table['prior'] * table['likelihood']
    prob_data = table['unnorm'].sum()
    table['posterior'] = table['unnorm'] / prob_data
    return prob_data

In [11]:
prob_data=update(table)
table

   prior likelihood1 likelihood2 likelihood  unnorm posterior
4    1/5           0           0          0       0         0
6    1/5           0         1/6          0       0         0
8    1/5           0         1/8          0       0         0
12   1/5        1/12        1/12      1/144   1/720     25/34
20   1/5        1/20        1/20      1/400  1/2000      9/34

In [15]:
table['posterior_float'] = table['posterior'].apply(lambda x: round(float(x), 4))
table

   prior likelihood1 likelihood2 likelihood  unnorm posterior  posterior_float
4    1/5           0           0          0       0         0           0.0000
6    1/5           0         1/6          0       0         0           0.0000
8    1/5           0         1/8          0       0         0           0.0000
12   1/5        1/12        1/12      1/144   1/720     25/34           0.7353
20   1/5        1/20        1/20      1/400  1/2000      9/34           0.2647